version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    container_name: smart-hive-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
    environment:
      - APP_ENV=production
      - DB_HOST=mysql
      - DB_DATABASE=smart_hive
      - DB_USERNAME=root
      - DB_PASSWORD=smart_hive_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - smart-hive-network

  mysql:
    image: mysql:8.0
    container_name: smart-hive-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: smart_hive_password
      MYSQL_DATABASE: smart_hive
      MYSQL_USER: smart_hive_user
      MYSQL_PASSWORD: smart_hive_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./build/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - smart-hive-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smart-hive-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: smart_hive_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - smart-hive-network

volumes:
  mysql_data:
    driver: local

networks:
  smart-hive-network:
    driver: bridge